#!/bin/bash
# /usr/bin/i3exit

logind=systemctl

case "$1" in
    lock)
        "${HOME}"/.config/i3/lock.sh
        ;;
    logout)
        i3-msg exit
        ;;
    suspend)
        "${HOME}"/.config/i3/lock.sh && $logind suspend
        ;;
    hibernate)
        "${HOME}"/.config/i3/lock.sh && $logind hibernate
        ;;
    reboot)
        $logind reboot
        ;;
    shutdown)
        $logind poweroff
        ;;
    *)
        echo "== ! i3exit: missing or invalid argument ! =="
        echo "Try again with: lock | logout | suspend | hibernate | reboot | shutdown"
        exit 2
esac

exit 0
