# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

# Use a different color for the status bar for remote sessions
if-shell 'test -n "$SSH_CLIENT"' \
   'set -g status-style bg=colour22,fg=colour231' \
   'set -g status-style bg=colour238,fg=colour231'

# Add binding for reloading the config
bind-key C-t source-file "${HOME}/.config/tmux/tmux.conf" \; display "Config Reloaded !"

# Switch windows with Alt+arrows
bind -n M-Right next-window
bind -n M-Left previous-window

# Increase history buffer size
set-option -g history-limit 50000

# Start window number from one, not zero
set -g base-index 1
setw -g pane-base-index 1

# Add easier to remember split window shortcuts
# Also, open them in the current directory
bind-key | split-window -h -c "#{pane_current_path}" 
bind-key _ split-window -v -c "#{pane_current_path}"

# Enable mouse mode
set -g mouse on

# Set cursor color
set -g cursor-colour white

# Better word-separators, default ones don't select full filename, paths etc
set -g word-separators ' @"=()[]'

# Configure color support: use 256-color mode and enable truecolor for terminals that support it
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

# Allow passtrough of escape sequences
set -g allow-passthrough all

# Override default behaviour which opens login shells
set -g default-command "${SHELL}"

# Single shortcut search
bind-key -T prefix C-r copy-mode \; send-keys C-r
bind-key -T prefix C-s copy-mode \; send-keys C-S

# tmux-resurrect
set -g @resurrect-save 'S'
set -g @resurrect-restore 'R'
set -g @resurrect-processes '"~emacs -nw->emacs -nw"'
set -g @continuum-restore 'on'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.config/tmux/plugins/tpm/tpm'
